### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Prvdnx** [pasqualerossi/Get_Next_Line#1]
Your resources are truly inspiring and helpful. Does this Simpler version of get_next_line follows the 42 guidelines?

**Comment by pasqualerossi** [comment]
We are not 100% sure, we haven't tested it through Moulinette yet. It passes all get_next_line testers that we have used.  Your more then welcome to use it and let us know if it does pass Moulinette.

**Comment by Prvdnx** [comment]
I was wondering, why did you use 7000000 for the buffer size?

**Comment by Prvdnx** [comment]
I was wondering, why did you use 7000000 for the line size?

**Comment by pasqualerossi** [comment]
i think at the time i used it for testing purposes, I don't think it has to be that big.

**Comment by Prvdnx** [comment]
It doesn't pass Moulinette because the subject requires it should be read with BUFFER_SIZE(dynamic) and not just "1"

**Comment by pasqualerossi** [comment]
share the code and I'll update the repo.
